name: Auto Update Schedule
on:
  schedule:
    - cron: '30 * * * *' # Запуск кожні півгодини (на 30-й хвилині)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 cloudscraper

      - name: Run parser
        run: python parser.py

      - name: Commit and push
        run: |
          git config --global user.name "SvitloBot"
          git config --global user.email "bot@example.com"
          git add schedule.json
          git commit -m "Auto-update schedule $(date)" || exit 0
          git push
